[DATABASE]
; FOR NT LOGIN
;
;ACTIVITY
;InventoryConnection=Provider=SQLOLEDB.1;Integrated Security=SSPI;Persist Security Info=False;Initial Catalog=Inventory;Data Source=172.16.0.2
;ActivityConnection=Provider=SQLOLEDB.1;Integrated Security=SSPI;Persist Security Info=False;Initial Catalog=Activity;Data Source=172.16.0.2
;ALCConnection=Provider=SQLOLEDB.1;Integrated Security=SSPI;Persist Security Info=False;Initial Catalog=VehicleOrder;Data Source=172.16.0.2



; FOR SQL LOGIN
;InventoryConnection=Provider=SQLOLEDB.1;Password=noway!;Persist Security Info=True;User ID=sa;Initial Catalog=Inventory;Data Source=172.18.51.9
;ActivityConnection=Provider=SQLOLEDB.1;Password=noway!;Persist Security Info=True;User ID=sa;Initial Catalog=Activity;Data Source=172.18.51.9
;ALCConnection=Provider=SQLOLEDB.1;Password=noway!;Persist Security Info=True;User ID=sa;Initial Catalog=VehicleOrder;Data Source=172.18.51.9

InventoryConnection=Provider=SQLOLEDB.1;Password=noway!;Persist Security Info=True;User ID=Inventory;Initial Catalog=Inventory;Data Source=DVERESPE-CD6D24\MSSQL2008
ActivityConnection=Provider=SQLOLEDB.1;Password=noway;Persist Security Info=True;User ID=Inventory;Initial Catalog=Activity;Data Source=DVERESPE-CD6D24
ALCConnection=Provider=SQLOLEDB.1;Password=noway!;Persist Security Info=True;User ID=Inventory;Initial Catalog=VehicleOrder;Data Source=DVERESPE-CD6D24\MSSQL2008

[SITE]
SupplierCode=93050
Assembler=HERO
PlantName=TMMTX
FileALC=FALSE
POEDISupport=True

TruckEnable=True
;PassEnable=True
PassEnable=False
GenerateEDI=True
RevSeqLookup=-45
TLineName=Tundra
ExcelOrderSheet=True

[DIRECTORIES]
ForecastFilename=nummi.prelftp
;ForecastFilename=*.txt
ForecastInputDir=C:\Inventory\Forecasting
ForecastInputDir=C:\Inventory_Control\EDIIn
ReportsOutputDir=C:\Inventory\Reports
LogisticsFilename=LDTrace.txt
LogisticsInputDir=C:\Inventory\EDI
TextShippingFileDir=C:\Daily Camex Results
EDIOut=C:\Inventory\EDIOut
EDIIn=C:\Inventory\EDIIn
TemplateDir=C:\Inventory\Templates
UseApplicationDir=False

[INIT]
ForecastUsageCompare=7
UsageUpdateCompare=14
LocalFTP=True
UseFirstProductionDay=True
;UseFirstProductionDay=FALSE
HistoricalForecast=12
FillDays=40
ConfirmOrderFileCreation=True
CreatePOPriorToClose=True

[DISPLAY]
HideTerminated=True
BuildOut=True
TruckSeqLength=3

[DATAPURGE]
EnableDataPurge=False
PromptDataPurge=True
DataRetention=12
PurgeRate=Daily
PurgeDayWeekly=Wednesday
LastPurge=2018020712002200
PurgeDayMonthly=1st





