#!/usr/bin/env python3
"""
build_fonts_css.py — regenerate docs/design/themes/tai/fonts.css with the woff2 files
in docs/design/themes/fonts/ embedded as base64 data-URIs.

Why embed instead of url(): the gateway's /res/perspective/fonts route only serves the
Perspective module's *bundled* fonts — woff2 dropped into data/modules/.../fonts/ are
NOT served (404 even after a restart). Embedding makes the suite fonts portable across
gateways and works on offline / locked-down plant clients. `local()` is listed first so
an installed copy wins and the data-URI is never decoded.

Run after adding/replacing a woff2, then redeploy tai/fonts.css to the gateway theme dir
and `touch` the entry file (tai-light.css / tai-dark.css) so the gateway recompiles the
theme (the theme watcher keys off the ENTRY file's mtime, not imported partials).
"""
import base64, os

THEMES = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
                      "ignition", "themes")

# (css family, local() name, weight, woff2 path under themes/fonts/)
FACES = [
    ("Inter", "Inter Regular",  400, "Inter/inter-latin-400-normal.woff2"),
    ("Inter", "Inter Medium",   500, "Inter/inter-latin-500-normal.woff2"),
    ("Inter", "Inter SemiBold", 600, "Inter/inter-latin-600-normal.woff2"),
    ("Inter", "Inter Bold",     700, "Inter/inter-latin-700-normal.woff2"),
    ("JetBrains Mono", "JetBrains Mono SemiBold", 600, "JetBrainsMono/jetbrains-mono-latin-600-normal.woff2"),
    ("JetBrains Mono", "JetBrains Mono Bold",     700, "JetBrainsMono/jetbrains-mono-latin-700-normal.woff2"),
]

def main():
    out = ["/* Self-hosted suite fonts (Inter + JetBrains Mono, SIL OFL, latin subset),",
           "   embedded as base64 data-URIs. GENERATED by scripts/build_fonts_css.py —",
           "   do not hand-edit. See that script for why embedding (vs a served url())."]
    for fam, lname, w, rel in FACES:
        with open(os.path.join(THEMES, "fonts", rel), "rb") as f:
            b = base64.b64encode(f.read()).decode()
        out.append('@font-face { font-family: "%s"; font-style: normal; font-weight: %d; font-display: swap;' % (fam, w))
        out.append('    src: local("%s"), url("data:font/woff2;base64,%s") format("woff2"); }' % (lname, b))
    dest = os.path.join(THEMES, "tai", "fonts.css")
    with open(dest, "w") as f:
        f.write("\n".join(out) + "\n")
    print("wrote %s (%d bytes, %d faces)" % (dest, os.path.getsize(dest), len(FACES)))

if __name__ == "__main__":
    main()
