[DATABASE]
; FOR NT LOGIN
;
;InventoryConnection=Provider=SQLOLEDB.1;Integrated Security=SSPI;Persist Security Info=False;Initial Catalog=InventoryT;Data Source=FAILPROOF1
;InventoryConnection=Provider=SQLOLEDB.1;Integrated Security=SSPI;Persist Security Info=False;Initial Catalog=Inventory2;Data Source=FAILPROOF1
;InventoryConnection=Provider=SQLOLEDB.1;Integrated Security=SSPI;Persist Security Info=False;Initial Catalog=InventoryH;Data Source=FAILPROOF1
;InventoryConnection=Provider=SQLOLEDB.1;Integrated Security=SSPI;Persist Security Info=False;Initial Catalog=Inventory2;Data Source=207.101.246.41
;ActivityConnection=Provider=SQLOLEDB.1;Integrated Security=SSPI;Persist Security Info=False;Initial Catalog=Activity;Data Source=FAILPROOF1
;ALCTruckConnection=Provider=SQLOLEDB.1;Integrated Security=SSPI;Persist Security Info=False;Initial Catalog=VehicleOrderHERO;Data Source=FAILPROOF1
;ALCPassConnection=Provider=SQLOLEDB.1;Integrated Security=SSPI;Persist Security Info=False;Initial Catalog=VehicleOrderHERO;Data Source=FAILPROOF1
;ALCPassConnection=Provider=SQLOLEDB.1;Integrated Security=SSPI;Persist Security Info=False;Initial Catalog=VehicleOrder;Data Source=FAILPROOF1


; FOR SQL LOGIN
;

InventoryConnection=Provider=SQLOLEDB.1;Password=noway;Persist Security Info=True;User ID=Inventory;Initial Catalog=InventoryI;Data Source=172.16.1.11
ALCConnection=Provider=SQLOLEDB.1;Password=noway;Persist Security Info=True;User ID=VehicleOrder;Initial Catalog=VehicleOrderSIA;Data Source=172.16.1.11
ActivityConnection =Provider=SQLOLEDB.1;Password=noway;Persist Security Info=True;User ID=Inventory;Initial Catalog=Activity;Data Source=172.16.1.11


[SITE]
;SupplierCode=93040
;Assembler=CAMEX
;PlantName=TMMBC
;FileALC=TRUE
;POEDISupport=True
;GenerateEDI=False

;SupplierCode=05680
;Assembler=WQS
;PlantName=NUMMI
;FileALC=FALSE
;POEDISupport=False


;SupplierCode=94050
;Assembler=HERO
;PlantName=TMMTX
;FileALC=FALSE
;POEDISupport=True
;GenerateEDI=True

SupplierCode=95500
Assembler=WWW
PlantName=TMMNK
FileALC=FALSE
POEDISupport=True
GenerateEDI=True

;TruckEnable=True
TruckEnable=False
;PassEnable=False
PassEnable=True
UseBCRatio=False
RevSeqLookup=-50
ExcelOrderSheet=True

[DIRECTORIES]
;ForecastFilename=nummi.prelftp
ForecastFilename=*.*
;ForecastInputDir=C:\_Inventory_Control\Forecast
ForecastInputDir=C:\EDI\EDIIn\Archive
ReportsOutputDir=R:\Inventory Reports
LogisticsFilename=Trace.txt
LogisticsInputDir=O:\Logistics
TextShippingFileDir=D:\Daily Camex Results\
EDIOut=X:\EDIOut
EDIIn=X:\EDIIn


[INIT]
ForecastUsageCompare=7
UsageUpdateCompare=14
LocalFTP=True
UseFirstProductionDay=TRUE
;UseFirstProductionDay=FALSE
HistoricalForecast=12
FillDays=23
ConfirmOrderFileCreation=True

[DISPLAY]
HideTerminated=False
BuildOut=False
TruckSeqLength=3
PassSeqLength=3

[DATAPURGE]
EnableDataPurge=True
PromptDataPurge=True
DataRetention=18
PurgeRate=Daily
PurgeDayMonthly=1st
LastPurge=2011092606283300
